### ISSUE TITLE
Undefined property: Omnipay\Datatrans\Message\XmlResponse::$httpRequest

### ISSUE THREAD

**Issue by fredtro** [w-vision/omnipay-datatrans#3]
Hi there

Using XmlGateway results in an error. Is it possible that:

`
 public function getData(
{
     return $this->httpRequest->request->all();
 }
`

Should be:

`
 public function getData(
{
     return $this->data;
 }
`

Thank you

**Comment by dpfaffenbauer** [comment]
possible, have you tested it? Does it work? We actually don't use the XML Gateway...

**Comment by fredtro** [comment]
Yes, it will return the array version of the xml result/response. Should i create a pull request?

**Comment by dpfaffenbauer** [comment]
sounds good to me 👍

**Comment by fredtro** [comment]
Perfect. 
Additionally i have notices that datatrans service urls are outdated (https://www.datatrans.ch/en/technology_apis/important-changes). But i will create another pull request for it, so you just have to hit ok 😬

**Comment by dpfaffenbauer** [comment]
ok :)

**Comment by fredtro** [comment]
I close this issue due to merged pull request which fixed it.
